@API_Server_HostAddress = http://localhost:5224

### Register a new user
POST {{API_Server_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "TestUser",
  "email": "test@brokey.app",
  "password": "Test1234!",
  "baseCurrency": "EUR"
}

### Login
POST {{API_Server_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test@brokey.app",
  "password": "Test1234!"
}

### Get current user profile
GET {{API_Server_HostAddress}}/api/auth/me
Authorization: Bearer <TOKEN>

###
